### ISSUE TITLE
Error: No metadata was found

### ISSUE THREAD

**Issue by bourgeoa** [solid/ldflex-playground#1]
as you can see with these images, when : 
. logged in or out and using my URI it doesn't found anything
. logged in with my webid and using .user it finds Alain Bourgeois
. logged out with URI ['https://ruben.verborgh.org/profile/#me'] it found Ruben Verborgh

![2018-11-09 1](https://user-images.githubusercontent.com/2218470/48258009-72205300-e414-11e8-9b73-ba92fbb3cc70.png)
![2018-11-09 2](https://user-images.githubusercontent.com/2218470/48258015-7482ad00-e414-11e8-9d94-39b76340d72e.png)
![2018-11-09 3](https://user-images.githubusercontent.com/2218470/48258634-dbed2c80-e415-11e8-8ac5-87f9f3c73c34.png)
![2018-11-09 4](https://user-images.githubusercontent.com/2218470/48258638-ddb6f000-e415-11e8-901a-5686b87ca842.png)

**Comment by RubenVerborgh** [comment]
Weird, it works for me. Any chance this was a temporary network problem?
If you try it again, any errors in the console?

The expression `['https://bourgeoa.solid.community/profile/card#me'].name` works fine when I try it. (Logging in or out should not make a different for that expression.) Note how the SPARQL queries are the same, so the results should be, too.

**Comment by bourgeoa** [comment]
I tried on Chrome browser and have the same problem
Before it was with Firefox

I noted that SPARQL query are the same

Here is the console error : 

evaluateExpressions.js:168 @solid/react-components Expression evaluation failed. Error: No metadata was found
    at t.<anonymous> (ActorRdfResolveQuadPatternFederated.js:126)
    at t.r.emit (events.js:68)
    at t.f._changeState (asynciterator.js:151)
    at t.f._end (asynciterator.js:294)
    at h (asynciterator.js:303)
    at p.run (index.js:92)
    at MutationObserver.l (index.js:44)
(anonymous) @ evaluateExpressions.js:168
Promise.catch (async)
(anonymous) @ evaluateExpressions.js:167
(anonymous) @ evaluateExpressions.js:166
w @ runtime.js:63
(anonymous) @ runtime.js:282
e.(anonymous function) @ runtime.js:116
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:29
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ evaluateExpressions.js:200
value @ evaluateExpressions.js:106
Po @ react-dom.production.min.js:5309
No @ react-dom.production.min.js:5017
Io @ react-dom.production.min.js:4983
De @ react-dom.production.min.js:5783
Le @ react-dom.production.min.js:670
Ir @ react-dom.production.min.js:1762
Fo @ react-dom.production.min.js:5481
Ar @ react-dom.production.min.js:1739

**Comment by RubenVerborgh** [comment]
@bourgeoa Thanks, I ran into the `No metadata was found` error myself this morning, so you're not alone. Will investigate.

**Comment by rubensworks** [comment]
Just tested this with Comunica itself, and the error doesn't seem to occur there: http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fmistermagoo.inrupt.net%2Fprofile%2Fcard%23me&query=SELECT%20%3FfirstName%20WHERE%20%7B%0A%20%20%3Chttps%3A%2F%2Fmistermagoo.inrupt.net%2Fprofile%2Fcard%23me%3E%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2Fknows%3E%20%3Fv0.%0A%20%20%3Fv0%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FgivenName%3E%20%3FfirstName.%0A%7D

In any case, the error definitely originates from within Comunica. It has something to do with the federated actor receiving an end event before a metadata event. Not sure exactly why though.

**Comment by RubenVerborgh** [comment]
After investigation, @rubensworks found that this could be traced back to a webpack rule for the asynciterator package that we didn't have. I updated the asynciterator package, and things are working now.
