### ISSUE TITLE
github pages deployment not working

### ISSUE THREAD

**Issue by angelo-v** [solid/ldflex-playground#13]
The ldflex playground seems to have moved here, but the link in the sidebar still points to https://solid.github.io/ldflex-playground/

The deployment at 

https://ldflex.github.io/Solid-Playground/

is not working, since it also tries to load JS from the old URL.

**Comment by RubenVerborgh** [comment]
Ah shoot, that's a pity. Thanks for reporting!

**Comment by RubenVerborgh** [comment]
Should be fixed by 277469617e4ed12208bc2c46cdd00cb36f364828
