### ISSUE TITLE
Same error as above

### ISSUE THREAD

**Issue by bourgeoa** [solid/ldflex-playground#2]
For me I got the same symptoms as prior issue but no error on console
Thanks for solving prior problem

**Comment by RubenVerborgh** [comment]
Hmmm, did you hard refresh your browser? It works for me and there was
indeed a bug before.

**Comment by bourgeoa** [comment]
I made it work with my URI by changing #me by card#me
For your URI do not add 'card'

Reason: CORS header ‘Access-Control-Allow-Origin’ missing
Reason: CORS request did not succeed

**Comment by RubenVerborgh** [comment]
> I made it work with my URI by changing #me by card#me
> For your URI do not add 'card'

Yes; it's very important to note that _no_ structure should be assumed for WebIDs, e.g., they don't have to have `card` or even `#me`.

Your WebID is `https://bourgeoa.solid.community/profile/card#me`, mine is `https://ruben.verborgh.org/profile/#me`.

**Comment by bourgeoa** [comment]
I am on the learning curve, but I never thought that **solid webid's** could be so different.
I don't seem to so that anywhere in documentation. Is there any explanation by the way ?
Does it come from solid-server version ? I used 3 different personal ones from 4.2 to 4.3.1 and allways show the same type.

**Comment by RubenVerborgh** [comment]
> I am on the learning curve, but I never thought that **solid webid's** could be so different.

First of all, WebIDs exist outside of Solid as well. So Solid does not mandate what a WebID should look like.

In general, nothing in Linked Data can or should be derived from a URL. So URLs can have any form or shape, and that does not say anything about there contents.

> I don't seem to so that anywhere in documentation.

You're right, this is one of the assumptions we have that we did not make explicit.

> Does it come from solid-server version ?

In my case, I have a WebID that is external to Solid, which explains the different URL structure.

But even within Solid, people could move their WebIDs.

So a WebID is really a string that should be used as-is.

**Comment by bourgeoa** [comment]
Thank you for your nice response;
Is there a way to display the graph of used data in a pod and/or used in an app like for exemple node-solid-server app. It could be a help for newbies to have a beginning of understanding of linked data seen on a practical usable way.

**Comment by RubenVerborgh** [comment]
I don't know names of such tools, but I do assume they exist. "RDF visualization" should be a good search term.
